[IZPACK-1698] Internalization of CustomPanel is not available in SummaryPanel
izpack/izpack pull request #744
Opened 2021-11-07 06:08 UTC by hiteshbosamiya

2021-11-08 07:21 UTC, reinhapa commented
@hiteshbosamiya can you also provide a JUnit test for the enhanced behavior.

2021-11-08 10:28 UTC, hiteshbosamiya commented
Added JUnit test for enhanced behavior.

2021-11-08 13:10 UTC, akuhtz requested changes

2021-11-08 13:10 UTC, akuhtz commented on izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
> +                    || id.startsWith(Resources.USER_INPUT_TRANSLATIONS_RESOURCE_NAME)
Can ```LANG_FILE_NAME``` then be removed from ```UserInputPanelSpec``` ?

2021-11-08 13:53 UTC, hiteshbosamiya commented
Removed `LANG_FILE_NAME` from `UserInputPanelSpec`.

2021-11-08 13:55 UTC, hiteshbosamiya commented on izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
> +                    || id.startsWith(Resources.USER_INPUT_TRANSLATIONS_RESOURCE_NAME)
Done

2021-11-08 18:38 UTC, akuhtz approved these changes

2021-11-12 09:54 UTC, hiteshbosamiya commented
@reinhapa, can you please look into this PR now as it has been approved by @akuhtz? Thanks.

2021-11-25 21:39 UTC, merged

2021-11-25 21:40 UTC, reinhapa commented
Closes #741