only append quotes when required
izpack/izpack pull request #761
Opened 2021-12-01 14:12 UTC by Vik-Git

This should resolve the following problem on linux (ubuntu) when doing a re-install.

`[ Starting processing ]
Starting process Remove Previously Installed Service (1/1)
I/O error:
java.io.IOException: Cannot run program ""/usr/local/app/uninstall-service.sh"": error=2, No such file or directory`

Note the double quotes in the exception, caused by a recent PR:
 https://github.com/izpack/izpack/pull/749

2021-12-07 07:49 UTC, hiteshbosamiya requested changes
Good point, can you please change the commit message as below?
[IZPACK-508] Execution of executable that contains "(" character fails - only append quotes when required

Also, please add PR link to the ticket https://izpack.atlassian.net/browse/IZPACK-508.

2021-12-12 17:19 UTC, Vik-Git commented
> Good point, can you please change the commit message as below? [IZPACK-508] Execution of executable that contains "(" character fails - only append quotes when required
> 
> Also, please add PR link to the ticket https://izpack.atlassian.net/browse/IZPACK-508.

This should be ok now?

2021-12-13 01:33 UTC, hiteshbosamiya commented
> > Good point, can you please change the commit message as below? [IZPACK-508](https://izpack.atlassian.net/browse/IZPACK-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) Execution of executable that contains "(" character fails - only append quotes when required
> > Also, please add PR link to the ticket https://izpack.atlassian.net/browse/IZPACK-508.
> 
> This should be ok now?

Looks good, thanks.

2021-12-13 18:19 UTC, akuhtz approved these changes

2021-12-14 07:47 UTC, merged

2022-01-07 08:18 UTC, ThibLind commented
Hello,

I have some problems with this patch. It doesn't seem to solve the initial problem.
I have written a little example that reproduce the problem (https://gist.github.com/ThibLind/e74efea815ea2c9f08fe634724135606). In fact, on my Debian (tested with jdk8 and jdk11), I obtain "java.io.IOException: Cannot run program ""/usr/bin/xclock"": error=2, Aucun fichier ou dossier de ce type"

Sincerely,

Thibault L.

2022-01-07 12:09 UTC, hiteshbosamiya commented
@ThibLind, can you please try your test program by changing the if condition as below and let us know the result?
`if (System.getProperty ("os.name").contains("Windows") && !(filename.startsWith("\"") && filename.endsWith("\"")))`

2022-01-07 14:16 UTC, ThibLind commented
@hiteshbosamiya, its work on Debian and on Windows too ! Thanks. Do I need to make a PR ?

2022-01-07 14:28 UTC, hiteshbosamiya commented
@ThibLind, yes, please raise a PR. You need to add the PR link to the ticket and the commit message should be "[IZPACK-508] Execution of executable that contains "(" character fails - taking care of Linux issue".

2022-01-10 07:16 UTC, ThibLind commented
Hello, here is the link of my PR : https://github.com/izpack/izpack/pull/763