[IZPACK-1425] User is not notified about temp file installer lock existence during automated installation
izpack/izpack pull request #774
Opened 2022-02-21 13:20 UTC by hiteshbosamiya

2022-02-28 06:34 UTC, reinhapa requested changes

2022-02-28 06:34 UTC, reinhapa commented on izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/LockFileChecker.java
> +            return true;
I would leave the single point of return the value

2022-02-28 06:34 UTC, reinhapa commented on izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/LockFileChecker.java
> -        logger.fine("Lock File Exists, asking user for permission to proceed.");
I would leave the single point of return the value

2022-02-28 06:34 UTC, reinhapa commented on izpack-installer/src/main/java/com/izforge/izpack/installer/requirement/LockFileChecker.java
> +            msg.append(" delete the lock file \"");
Do we not need any new lines here? Also if we have the same line feeds as within the GUI, extracting the identical parts into a separate method would make sense.

2022-03-01 11:42 UTC, hiteshbosamiya commented
As per IZPACK-963, we need to localize the messages. Closing this PR and raise another PR once https://github.com/izpack/izpack/pull/773 is merged

2022-03-01 11:42 UTC, closed without merging